config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
    resources :posts do
  	resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	has_rich_text :content
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 5000}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments

  validates :name, presence: true, length: {maximum: 50}
  before_save {self.email = email.downcase}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 250}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}

  validates :password, presence: true, length: {maximum: 6}
  validates :password_confirmation, presence: true, length: {maximum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    attributes = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post_id_for_comments, only: [:create, :destroy]
  
	def create
		@comment = @post.comments.create(comments_params)
		if @comment.save
      redirect_to @post
    else
      redirect_to post_path(@post)
    end
	end

	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to @post
	end

	private

	def comments_params
		params.require(:comment).permit(:body)
	end

  def set_post_id_for_comments
    @post = Post.find(params[:post_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:destroy, :edit, :update]
	before_action :authenticate_user!, except: [:show, :index]

	def index
		@posts = Post.all
	end

	def create
		@post = current_user.posts.build(posts_params)
		if @post.save
		  flash.now[:success] = "Your blog has been created and posted to your profile page....."
		  redirect_to @post
		else
		  render 'new'
		end
	end

	def destroy
		@post.destroy
		flash[:success] = "Your Blog has been deleted successfully."
		redirect_to @post
	end

	def new
		@post = Post.new(params[:post])
	end

	def edit
	end

	def update
		if @post.update(posts_params)
		  flash[:success] = 'Your Post is updated'
		  redirect_to @post
    else
      render 'edit'
    end
	end

	def show
		@post = Post.find_by_id(params[:id])
	  @comment = Comment.new
	  @comments = @post.comments
  end

	private

	def posts_params
		params.require(:post).permit(:content)
	end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<% @comments.each do |c| %>
  <p>
    <%= @post.user.name %><a> :- </a>
    <%= c.body %>
    <%= link_to "Delete", post_comment_path(c.post_id, c.id), method: :delete, data: {confirm: "Are you sure?"} %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@post, @comment]) do |f| %>
  <p>
  	<%= f.label :body %>
  	<%= f.text_area :body %></br>
  </p>

  <p>
  	<%= f.submit "Add a comment" %>
  </p>
<%end %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Blog app </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Blog", '#', id: "logo" %>
          <nav>
            <ul class="nav navbar-nav navbar-right">
               <% if !current_user.nil? %> 
                <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
              <% end %>
            </ul>
          </nav>
      </div>
    </header>
    <div class="container">
      <%= render 'layouts/alerts'%>
    </div>      
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Blog</h1>

<% if current_user %>
  <%= link_to "Add a Post", new_post_path, class: "btn btn-lg btn-primary"%>
<% else %>
  <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Sign in", new_user_session_path, class: "btn btn-lg btn-primary" %>
<% end %>

<%= link_to 'Posts', posts_path, class: "btn btn-lg btn-primary" %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <b>Post By:-   <%= post.user.name %> </b>
    <% if current_user %>
      <%= link_to 'show post', post_path(post), class: "btn btn-lg btn-primary" %>
    <% end %>
  </span>
</li>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for(@post) do |f| %>
  <div class="field">
  	<%= f.label :style_content %>
    <%= f.rich_text_area :content, placeholder: "Compose new post..." %>
  </div><%= f.submit "Update Post", class: "btn btn-primary" %>
<% end %>

app/views/posts/index.html.erb
<% if current_user %>
<h3></a><%= current_user.name %>'s  posts on blog app(<%= current_user.posts.count %>)</h3>
<% end %>
<ol class="posts">
  <%= render @posts %>
</ol>

<%= link_to "Add a Post", new_post_path, class: "btn btn-lg btn-primary"%>

app/views/posts/new.html.erb
<h1>Compose Post</h1>
<%= form_for(@post) do |f| %>
  <div class="field">
  	<%= f.label :style_content %>
    <%= f.rich_text_area :content, placeholder: "Compose new post..." %>
  </div><%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Show all Posts', posts_path, class: "btn btn-lg btn-primary" %>

app/views/posts/show.html.erb
<h1><%= @post.user.name %></h1>
<p>
  <strong>Body:</strong>
  <%= @post.content %>
</p>
<br>
<div class="col-md-8">        
  <h2> Comments </h2>
  <%= render 'comments/comment' %>
  <h3>Add a Comment: </h3>
  <%= render 'comments/form'%>       
</div>
<br>
<%= link_to "Add a Post", new_post_path, class: "btn btn-lg btn-primary"%>

<%= link_to 'Show all Posts', posts_path, class: "btn btn-lg btn-primary" %>

<% if current_user.id == @post.user_id %>
  <%= link_to 'Edit Post', edit_post_path(@post), class: "btn btn-lg btn-primary"%>
  <%= link_to "delete", @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-lg btn-primary" %>
<% end %>